### .rs active

GET localhost:8080/whois?domain_name=maxi.rs

### .rs not registered

GET localhost:8080/whois?domain_name=biratenepostojecibroj.rs

### .rs expired

GET localhost:8080/whois?domain_name=bravo.rs

### .rs reserved

GET localhost:8080/whois?domain_name=test.rs

### .rs expired

GET localhost:8080/whois?domain_name=bravo.rs

### .срб

GET localhost:8080/whois?domain_name=рнидс.срб

### .com

GET localhost:8080/whois?domain_name=donesi.com

### .com expired

GET localhost:8080/whois?domain_name=00ur.com

### .com not registered

GET localhost:8080/whois?domain_name=biratenepostojecibroj.com

### .com

GET localhost:8080/whois?domain_name=test.com

### .org

GET localhost:8080/whois?domain_name=helloworld.org

### .net

GET localhost:8080/whois?domain_name=test.net

### send email

POST localhost:8080/email?email_to=ivann990@gmail.com&domain_name=facebook.com
