### .rs

GET localhost:8080/whois?domain_name=maxi.rs

### not registered

GET localhost:8080/whois?domain_name=biratenepostojecibroj.rs

### expired

GET localhost:8080/whois?domain_name=bravo.rs

### .срб

GET localhost:8080/whois?domain_name=рнидс.срб

### .com

GET localhost:8080/whois?domain_name=facebook.com


